import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { unzipSync } from 'fflate';
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { spawn, execFileSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { inspectStaticPackage } from './inspect-static-package.mjs';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
let appRoot=root, archive;
const args=process.argv.slice(2);
for(let i=0;i<args.length;i++){if(args[i]==='--app-root'&&args[i+1])appRoot=path.resolve(args[++i]);else if(args[i]==='--package'&&args[i+1])archive=path.resolve(args[++i]);else throw new Error('Usage: acceptance-policy.mjs [--app-root extracted-root --package archive]');}
const packaged=appRoot!==root;if(packaged&&!archive)throw new Error('An exact package archive is required.');
const artifact=path.join(root,'artifacts','policy-'+randomUUID());await mkdir(artifact,{recursive:true});
const site=path.join(appRoot,packaged?'web':'dist');
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
async function identity(){
 const files=[];async function visit(dir,prefix=''){for(const entry of await readdir(dir,{withFileTypes:true})){if(!packaged&&!prefix&&entry.name==='cli')continue;const absolute=path.join(dir,entry.name),name=prefix+entry.name;if(entry.isDirectory())await visit(absolute,name+'/');else if(entry.isFile()){const bytes=await readFile(absolute);files.push({name,bytes:bytes.length,sha256:hash(bytes)});}else throw new Error('Unexpected asset type.');}}await visit(site);
 return {assets:files.sort((a,b)=>a.name.localeCompare(b.name)),...(packaged?{packageInspection:await inspectStaticPackage(archive,appRoot)}:{})};
}
const steps=[], errors=[],external=[];let browser,server,page,base;
const startedAt=new Date().toISOString();let sourceCommit=null,sourceState;
try{sourceCommit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim();sourceState={trackedChangedPaths:execFileSync('git',['diff','--name-only','HEAD'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean),untrackedPaths:execFileSync('git',['ls-files','--others','--exclude-standard'],{cwd:root,encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean)};}catch{}
async function step(name,run){const start=performance.now();await run();steps.push({name,status:'passed',durationMs:Math.round(performance.now()-start)});}
try{
 const initial=await identity();
 server=spawn(process.execPath,[path.join(appRoot,'scripts/serve.mjs'),'--root',site,'--port','0'],{cwd:os.tmpdir(),stdio:['ignore','pipe','pipe']});
 base=await new Promise((resolve,reject)=>{let out='',err='';const timer=setTimeout(()=>reject(new Error('Local server startup timed out: '+err)),10000);server.stderr.on('data',b=>err+=b);server.stdout.on('data',b=>{out+=b;if(out.includes('\n')){clearTimeout(timer);try{resolve(JSON.parse(out.split('\n')[0]).url);}catch(cause){reject(cause);}}});server.once('exit',()=>{clearTimeout(timer);reject(new Error('Local server exited before startup.'));});});
 browser=await chromium.launch({headless:true,chromiumSandbox:true});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1024}});page=await context.newPage();page.on('pageerror',cause=>errors.push(cause.message));page.on('request',req=>{if(!req.url().startsWith(base)&&!req.url().startsWith('blob:')&&!req.url().startsWith('data:'))external.push(req.url());});
 const choose=page.getByLabel('Choose HAR, log, or image files'),editor=page.getByLabel('Cleaned text, editable'),ack=page.getByRole('checkbox',{name:/I reviewed/i}),button=page.getByRole('button',{name:'Build and download ZIP',exact:true});
 const policyPanel=page.locator('.policy-panel');
 async function ready(count){await page.waitForFunction(n=>document.querySelectorAll('.status-ready').length===n,count,{timeout:30000});}
 async function fillReport(){for(const [label,value]of [['Title','Synthetic policy evidence'],['Steps to reproduce','Open the synthetic request.'],['Expected result','A successful request.'],['Actual result','HTTP 500.'],['Environment','Synthetic only.']])await page.getByLabel(label,{exact:true}).fill(value);}
 async function download(name,trigger){const pending=page.waitForEvent('download',{timeout:30000});await trigger();const downloaded=await pending;const file=path.join(artifact,name);await downloaded.saveAs(file);return readFile(file);}
 const baseline=JSON.parse(await readFile(path.join(appRoot,'examples/sample.har'),'utf8'));
 const har=structuredClone(baseline);const entry=har.log.entries[0];har.log.entries=[entry,structuredClone(entry),structuredClone(entry)];
 entry.request.postData={mimeType:'application/json',text:JSON.stringify({password:'BODY_PASSWORD_SEED',customer_id:'CUSTOM_FIELD_SEED',message:'hello PRIVATE_LITERAL_SEED',kept:42})};
 entry.response.content={mimeType:'application/x-www-form-urlencoded',text:'token=FORM_TOKEN_SEED&public=hello&customer_id=CUSTOM_FORM_SEED',size:70};
 har.log.entries[1].request.postData={mimeType:'application/x-www-form-urlencoded',text:'password=REQUEST_FORM_SEED&public=preserved'};
 har.log.entries[1].response.content={mimeType:'application/json',text:JSON.stringify({token:'RESPONSE_JSON_SEED',public:'preserved'}),size:55};
 har.log.entries[2].request.postData={mimeType:'application/json',text:'BINARY_BODY_SEED',encoding:'base64'};
 har.log.entries[2].response.content={mimeType:'application/json',text:'{"token":"AMBIGUOUS_BODY_SEED","token":"different"}',size:60};
 const harBytes=Buffer.from(JSON.stringify(har)),logBytes=Buffer.from('contact=PRIVATE_LITERAL_SEED\ntoken=LOG_POLICY_SECRET\n');
 const seeds=['BODY_PASSWORD_SEED','CUSTOM_FIELD_SEED','PRIVATE_LITERAL_SEED','FORM_TOKEN_SEED','CUSTOM_FORM_SEED','REQUEST_FORM_SEED','RESPONSE_JSON_SEED','BINARY_BODY_SEED','AMBIGUOUS_BODY_SEED','LOG_POLICY_SECRET'];
 for(const seed of seeds)assert.ok(Buffer.concat([harBytes,logBytes]).includes(Buffer.from(seed)));
 await writeFile(path.join(artifact,'synthetic-policy.har'),harBytes);await writeFile(path.join(artifact,'synthetic-policy.log'),logBytes);
 await step('default policy omits bodies in actual workers',async()=>{await page.goto(base);await choose.setInputFiles([{name:'policy.har',mimeType:'application/json',buffer:harBytes},{name:'policy.log',mimeType:'text/plain',buffer:logBytes}]);await ready(2);await page.getByRole('button',{name:'Select policy.har',exact:true}).click();assert.ok(!JSON.parse(await editor.inputValue()).log.entries[0].request.postData);await fillReport();await ack.check();assert.equal(await button.isEnabled(),true);});
 await step('policy application requires explicit discard consent and resets review',async()=>{await editor.fill((await editor.inputValue()).replace('500','501'));await ack.check();await policyPanel.locator('summary').click();await page.getByLabel('Policy name',{exact:true}).fill('PRIVATE_POLICY_NAME');await page.getByLabel('HAR body handling').selectOption('supported');await page.getByLabel('Extra sensitive field names').fill('customer_id');await page.getByRole('button',{name:'Add literal rule',exact:true}).click();await page.getByLabel('Match 1',{exact:true}).fill('PRIVATE_LITERAL_SEED');assert.equal(await page.getByRole('button',{name:'Apply policy',exact:true}).isEnabled(),false);await page.getByRole('checkbox',{name:/Rebuild text from the originals/}).check();await page.getByRole('button',{name:'Apply policy',exact:true}).click();await ready(2);assert.equal(await ack.isChecked(),false);assert.equal(await button.isEnabled(),false);const clean=JSON.parse(await editor.inputValue());assert.equal(clean.log.entries[0].response.status,har.log.entries[0].response.status);});
 await step('both request and response JSON and form bodies retain only cleaned supported structure',async()=>{const clean=JSON.parse(await editor.inputValue());const first=clean.log.entries[0];assert.deepEqual(JSON.parse(first.request.postData.text),{password:'[REDACTED]',customer_id:'[REDACTED]',message:'hello [REDACTED]',kept:42});assert.equal(new URLSearchParams(first.response.content.text).get('public'),'hello');assert.equal(new URLSearchParams(first.response.content.text).get('token'),'[REDACTED]');assert.equal(new URLSearchParams(clean.log.entries[1].request.postData.text).get('public'),'preserved');assert.equal(JSON.parse(clean.log.entries[1].response.content.text).public,'preserved');assert.ok(!clean.log.entries[2].request.postData);assert.ok(!('text' in clean.log.entries[2].response.content));});
 let policy;
 await step('saved policy is canonical local JSON and can be loaded for review',async()=>{const bytes=await download('saved-policy.json',()=>page.getByRole('button',{name:'Save policy file',exact:true}).click());policy=JSON.parse(bytes);assert.equal(policy.schemaVersion,1);assert.equal(policy.bodyMode,'supported');assert.ok(policy.sensitiveKeys.includes('customer_id'));assert.equal(policy.literalRules[0].value,'PRIVATE_LITERAL_SEED');await page.getByLabel('Load cleaning policy').setInputFiles({name:'saved.json',mimeType:'application/json',buffer:bytes});await page.getByRole('status').filter({hasText:'Policy loaded for inspection'}).waitFor();});
 await step('unknown policy version and ambiguous JSON are rejected without changing active policy',async()=>{for(const text of [JSON.stringify({...policy,schemaVersion:99}),'{"schemaVersion":1,"schemaVersion":1}']){await page.getByLabel('Load cleaning policy').setInputFiles({name:'bad-policy.json',mimeType:'application/json',buffer:Buffer.from(text)});await policyPanel.getByRole('alert').waitFor();assert.ok(await policyPanel.getByRole('alert').innerText());assert.ok((await policyPanel.locator('summary').innerText()).includes('PRIVATE_POLICY_NAME'));}});
 await step('actual schema 2 ZIP excludes seeded secrets and policy contents',async()=>{await page.getByLabel('Load cleaning policy').setInputFiles({name:'restored-policy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(policy))});await page.getByRole('status').filter({hasText:'Policy loaded for inspection'}).waitFor();assert.equal(await policyPanel.getByRole('alert').count(),0);await page.getByRole('button',{name:'Select policy.log',exact:true}).click();assert.ok(!(await editor.inputValue()).includes('PRIVATE_LITERAL_SEED'));const bytes=await download('policy-bundle.zip',async()=>{await ack.check();await button.click();});const zip=unzipSync(new Uint8Array(bytes));assert.deepEqual(Object.keys(zip).sort(),['bug-report.md','evidence-001.har','evidence-002.log','processing-summary.json']);const all=Buffer.concat(Object.values(zip).map(value=>Buffer.from(value)));for(const seed of [...seeds,'PRIVATE_POLICY_NAME'])assert.ok(!all.includes(Buffer.from(seed)),seed);const summary=JSON.parse(Buffer.from(zip['processing-summary.json']).toString());assert.equal(summary.schemaVersion,2);assert.equal(summary.policy.id,hash(Buffer.from(JSON.stringify(policy))));assert.equal(summary.policy.bodyMode,'supported');assert.deepEqual(Object.keys(summary.policy).sort(),['bodyMode','id','schemaVersion']);assert.ok(summary.files[0].omissions.some(row=>row.code==='body-binary'));assert.ok(summary.files[0].omissions.some(row=>row.code==='body-invalid'));await writeFile(path.join(artifact,'processing-summary.json'),JSON.stringify(summary,null,2)+'\n');await policyPanel.locator('summary').click();await page.screenshot({path:path.join(artifact,'policy-review.png'),fullPage:true});});
 await step('a reload restores default behavior without persisting private policy or evidence',async()=>{await page.reload();assert.equal(await page.locator('.file-row').count(),0);assert.ok((await policyPanel.locator('summary').innerText()).includes('BugPack default'));await choose.setInputFiles({name:'policy.har',mimeType:'application/json',buffer:harBytes});await ready(1);assert.ok(!JSON.parse(await editor.inputValue()).log.entries[0].request.postData);});
 await step('cancelling actual policy reprocessing reports failure and can recover',async()=>{
  await policyPanel.locator('summary').click();await page.getByLabel('HAR body handling').selectOption('supported');await page.getByRole('checkbox',{name:/Rebuild text from the originals/}).check();
  const cdp=await context.newCDPSession(page);let timer;
  const attached=new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(new Error('Policy worker did not attach paused.')),5000);cdp.on('Target.attachedToTarget',event=>{if(event.targetInfo.type==='worker'){clearTimeout(timer);resolve(event);}});});
  await cdp.send('Target.setAutoAttach',{autoAttach:true,waitForDebuggerOnStart:true,flatten:true});
  try{await page.getByRole('button',{name:'Apply policy',exact:true}).click();const target=await attached;assert.equal(target.waitingForDebugger,true);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.status-failed').length===1);await policyPanel.getByRole('alert').waitFor();assert.match(await policyPanel.getByRole('alert').innerText(),/failed or was cancelled/);assert.equal(await button.isEnabled(),false);}
  finally{clearTimeout(timer);await cdp.send('Target.setAutoAttach',{autoAttach:false,waitForDebuggerOnStart:false,flatten:true}).catch(()=>{});await cdp.detach();}
  await page.getByRole('button',{name:'Apply policy',exact:true}).click();await ready(1);await page.getByRole('status').filter({hasText:'Policy applied. Review'}).waitFor();assert.equal(await policyPanel.getByRole('alert').count(),0);
 });
 await step('full application package and synthetic source bytes remain unchanged',async()=>{assert.deepEqual(await identity(),initial);assert.equal(hash(await readFile(path.join(artifact,'synthetic-policy.har'))),hash(harBytes));assert.equal(hash(await readFile(path.join(artifact,'synthetic-policy.log'))),hash(logBytes));assert.deepEqual(errors,[]);assert.deepEqual(external,[]);});
 const pkg=JSON.parse(await readFile(path.join(appRoot,'package.json'),'utf8'));
 await writeFile(path.join(artifact,'acceptance.json'),JSON.stringify({schemaVersion:1,suite:'actual-browser-policies',status:'passed',version:pkg.version,packaged,sourceCommit,sourceState,platform:process.platform+'/'+process.arch,host:{node:process.version,osRelease:os.release(),chromium:browser.version()},startedAt,finishedAt:new Date().toISOString(),steps,identities:initial,syntheticSources:[{name:'synthetic-policy.har',bytes:harBytes.length,sha256:hash(harBytes)},{name:'synthetic-policy.log',bytes:logBytes.length,sha256:hash(logBytes)}],pageErrors:errors,unexpectedRequests:external},null,2)+'\n');
 console.log(JSON.stringify({status:'passed',suite:'actual-browser-policies',steps:steps.length,packaged,artifact}));
}catch(cause){await page?.screenshot({path:path.join(artifact,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(artifact,'failure.json'),JSON.stringify({status:'failed',packaged,sourceCommit,sourceState,startedAt,steps,error:String(cause.stack??cause),pageErrors:errors,unexpectedRequests:external},null,2)+'\n');throw cause;}
finally{await browser?.close();if(server){server.kill();await new Promise(resolve=>server.exitCode!==null?resolve():server.once('exit',resolve));}}
