import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { unzipSync } from 'fflate';
import { inspectStaticPackage } from './inspect-static-package.mjs';
import { readFile, writeFile, mkdir, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash, randomUUID } from 'node:crypto';
import { spawn, execFileSync } from 'node:child_process';
import os from 'node:os';
import http from 'node:http';
import { once } from 'node:events';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const args=process.argv.slice(2); let appRoot=root; let packageArchive;
for(let i=0;i<args.length;i++) { if(args[i]==='--app-root'&&args[i+1])appRoot=path.resolve(args[++i]); else if(args[i]==='--package'&&args[i+1])packageArchive=path.resolve(args[++i]); else throw new Error('Usage: node scripts/acceptance.mjs [--app-root extracted-package] [--package archive]'); }
const packaged=appRoot!==root; if(packaged&&!packageArchive)throw new Error('Packaged acceptance requires the exact archive.');
const site=path.join(appRoot,packaged?'web':'dist');
const artifact=path.join(root,'artifacts','acceptance-'+randomUUID());await mkdir(artifact,{recursive:true});
const hash=b=>createHash('sha256').update(b).digest('hex');
const manifest=JSON.parse(await readFile(path.join(root,'examples/manifest.json'),'utf8'));
const fixtureRoot=packaged?appRoot:root;
async function identities() {
 const shippedManifest=JSON.parse(await readFile(path.join(fixtureRoot,'examples/manifest.json'),'utf8'));assert.deepEqual(shippedManifest,manifest,'The packaged fixture manifest must match the source contract.');const fixtures=[];for(const f of manifest.files) {const b=await readFile(path.join(fixtureRoot,'examples',f.name));assert.equal(hash(b),f.sha256);assert.equal(b.length,f.bytes);fixtures.push({name:f.name,sha256:hash(b),bytes:b.length});}
 const assets=[];async function visit(dir,prefix='') {for(const e of await readdir(dir,{withFileTypes:true})){if(e.isDirectory()){if(!packaged && !prefix && e.name==='cli')continue;await visit(path.join(dir,e.name),prefix+e.name+'/');}else if(e.isFile()){const b=await readFile(path.join(dir,e.name));assets.push({name:prefix+e.name,bytes:b.length,sha256:hash(b)});}else throw new Error('Unsupported application file type.');}}await visit(site);assets.sort((a,b)=>a.name.localeCompare(b.name));
 return {fixtures,assets,...(packageArchive?{package:{bytes:(await stat(packageArchive)).size,sha256:hash(await readFile(packageArchive))}}:{})};
}
let initial,pkg,packageInspection;
let sourceCommit=null;let sourceState={trackedChangedPaths:[],untrackedPaths:[]};try {sourceCommit=execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();const gitLines=args=>execFileSync('git',args,{cwd:root,encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim().split(/\r?\n/).filter(Boolean).sort();sourceState={trackedChangedPaths:gitLines(['diff','--name-only','HEAD']),untrackedPaths:gitLines(['ls-files','--others','--exclude-standard'])};}catch{}
const steps=[];let browser,server,page;const pageErrors=[];const external=[];let canaryHits=0;
const canary=http.createServer((req,res)=>{canaryHits++;res.end('must remain unread');});canary.listen(0,'127.0.0.1');await once(canary,'listening');
let base;const startedAt=new Date().toISOString();
async function step(name,fn){const t=performance.now();await fn();steps.push({name,status:'passed',durationMs:Math.round(performance.now()-t)});}
try {
 initial=await identities();if(packaged){packageInspection=await inspectStaticPackage(packageArchive,appRoot);assert.equal(packageInspection.archiveSha256,initial.package.sha256);assert.equal(packageInspection.archiveBytes,initial.package.bytes);}const fixtureContents=Buffer.concat(await Promise.all(manifest.files.map(f=>readFile(path.join(fixtureRoot,'examples',f.name)))));for(const secret of manifest.secrets)assert.ok(fixtureContents.includes(Buffer.from(secret)),'Declared secret was not actually seeded: '+secret);pkg=JSON.parse(await readFile(path.join(appRoot,'package.json'),'utf8'));
 server=spawn(process.execPath,[path.join(appRoot,'scripts/serve.mjs'),'--root',site,'--port','0'],{cwd:appRoot,stdio:['ignore','pipe','pipe']});
 base=await new Promise((resolve,reject)=>{let s='',err='';const timer=setTimeout(()=>reject(new Error('Server did not start: '+err)),10000);server.stderr.on('data',b=>err+=b.toString());server.stdout.on('data',b=>{s+=b.toString();if(s.includes('\n')){clearTimeout(timer);try{resolve(JSON.parse(s.split('\n')[0]).url);}catch(e){reject(e);}}});server.on('exit',()=>{clearTimeout(timer);reject(new Error('Server exited: '+err));});});
 browser=await chromium.launch({headless:true,chromiumSandbox:true});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1024}});page=await context.newPage();page.on('pageerror',e=>pageErrors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
 let peakRss=process.memoryUsage().rss;const sampler=setInterval(()=>peakRss=Math.max(peakRss,process.memoryUsage().rss),200);sampler.unref();
 const choose=page.getByLabel('Choose HAR, log, or image files'); const ack=page.getByRole('checkbox',{name:/I reviewed/i});const exportButton=page.getByRole('button',{name:'Build and download ZIP',exact:true});
 async function ready(count){await page.waitForFunction(n=>document.querySelectorAll('.status-ready').length===n,count,{timeout:30000});}
 async function fillReport(){await page.getByLabel('Title',{exact:true}).fill('Synthetic request fails');await page.getByLabel('Steps to reproduce').fill('Open the synthetic page and submit.');await page.getByLabel('Expected result').fill('A success response.');await page.getByLabel('Actual result').fill('HTTP 500.');await page.getByLabel('Environment',{exact:true}).fill('Synthetic browser fixture.');}
 async function download(name){await ack.check();assert.equal(await exportButton.isEnabled(),true);const waiting=page.waitForEvent('download',{timeout:30000});await exportButton.click();const d=await waiting;const dest=path.join(artifact,name);await d.saveAs(dest);return unzipSync(new Uint8Array(await readFile(dest)));}
 await step('local startup and connection boundary',async()=>{const response=await page.goto(base);assert.equal(response.status(),200);assert.match(response.headers()['content-security-policy'],/connect-src 'none'/);assert.equal(await page.title(),'BugPack · Local evidence review');assert.equal(await exportButton.isEnabled(),false);const result=await page.evaluate(async url=>{try{await fetch(url);return 'unexpected-success';}catch{return 'blocked';}},'http://127.0.0.1:'+canary.address().port+'/canary');assert.equal(result,'blocked');assert.equal(canaryHits,0);external.length=0;});
 await step('HAR and UTF-8 log are processed in actual workers',async()=>{await choose.setInputFiles(['sample.har','sample.log','sample.png'].map(n=>path.join(fixtureRoot,'examples',n)));await ready(3);await page.getByRole('button',{name:'Select sample.har',exact:true}).click();const raw=await page.getByLabel('Original raw text, read only').inputValue();const clean=await page.getByLabel('Cleaned text, editable').inputValue();assert.ok(raw.includes(manifest.secrets[0]));for(const secret of manifest.secrets)assert.ok(!clean.includes(secret));assert.ok(!JSON.parse(clean).log.entries[0].request.postData);});
 await step('manual text review removes an uncovered personal value',async()=>{await page.getByRole('button',{name:'Select sample.log',exact:true}).click();const editor=page.getByLabel('Cleaned text, editable');const clean=await editor.inputValue();assert.ok(clean.includes(manifest.manualLogValue));assert.ok(!clean.includes('LOG_SEED_0123456789'));await editor.fill(clean.replaceAll(manifest.manualLogValue,'[REMOVED BY REVIEW]'));await fillReport();});
 await step('opaque whole-pixel masks regenerate the PNG',async()=>{await page.getByRole('button',{name:'Select sample.png',exact:true}).click();await page.getByRole('button',{name:/Add mask/}).click();for(const [key,value]of Object.entries(manifest.screenshotMask)){await page.getByLabel('Mask 1 '+(key==='x'?'X':key==='y'?'Y':key)).fill(String(value));}await page.getByRole('button',{name:'Apply masks and regenerate PNG',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.busy-banner'),null,{timeout:30000});await ack.waitFor({state:'visible'});await page.waitForFunction(()=>!Array.from(document.querySelectorAll('input[type=checkbox]')).find(e=>e.closest('.review-check'))?.disabled);});
 await step('editing invalidates the review acknowledgement',async()=>{await ack.check();await page.getByLabel('Title',{exact:true}).fill('Reviewed synthetic request fails');assert.equal(await ack.isChecked(),false);assert.equal(await exportButton.isEnabled(),false);});
 let exported;
 await step('actual exported ZIP contains only reviewed regenerated evidence',async()=>{exported=await download('reviewed-bundle.zip');assert.deepEqual(Object.keys(exported).sort(),['bug-report.md','evidence-001.har','evidence-002.log','evidence-003.png','processing-summary.json']);for(const [name,b]of Object.entries(exported)){assert.ok(!name.includes('..')&&!name.includes('sample'));for(const secret of manifest.secrets)assert.ok(!Buffer.from(b).includes(Buffer.from(secret)),name+' leaked '+secret);assert.ok(!Buffer.from(b).includes(Buffer.from(manifest.manualLogValue)));}const summary=JSON.parse(Buffer.from(exported['processing-summary.json']).toString('utf8'));assert.equal(summary.schemaVersion,1);const har=summary.files.find(f=>f.kind==='har');assert.ok(har.omissions.some(o=>o.code==='body'&&o.count>0),'original HAR body omissions must be retained');assert.equal(summary.files.find(f=>f.kind==='image').masks,1);await writeFile(path.join(artifact,'processing-summary.json'),JSON.stringify(summary,null,2)+'\n');});
 await step('reopened PNG mask pixels are opaque and metadata is absent',async()=>{const png=exported['evidence-003.png'];const types=[];for(let offset=8;offset<png.length;){const size=Buffer.from(png).readUInt32BE(offset);types.push(Buffer.from(png.subarray(offset+4,offset+8)).toString('ascii'));offset+=12+size;}assert.ok(types.every(t=>['IHDR','PLTE','IDAT','IEND'].includes(t)));const result=await page.evaluate(async({bytes,original,mask})=>{async function decode(b){const bitmap=await createImageBitmap(new Blob([new Uint8Array(b)],{type:'image/png'}));const c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;const ctx=c.getContext('2d');ctx.drawImage(bitmap,0,0);bitmap.close();return{width:c.width,height:c.height,pixels:ctx.getImageData(0,0,c.width,c.height).data};}const clean=await decode(bytes);const raw=await decode(original);let opaqueBlack=true;let unmaskedUnchanged=true;let unmaskedPixels=0;for(let y=0;y<clean.height;y++)for(let x=0;x<clean.width;x++){const i=(y*clean.width+x)*4;if(x>=mask.x&&x<mask.x+mask.width&&y>=mask.y&&y<mask.y+mask.height){if(clean.pixels[i]!==0||clean.pixels[i+1]!==0||clean.pixels[i+2]!==0||clean.pixels[i+3]!==255)opaqueBlack=false;}else{unmaskedPixels++;for(let k=0;k<4;k++)if(clean.pixels[i+k]!==raw.pixels[i+k])unmaskedUnchanged=false;}}return{width:clean.width,height:clean.height,opaqueBlack,unmaskedUnchanged,unmaskedPixels};},{bytes:Array.from(png),original:Array.from(await readFile(path.join(fixtureRoot,'examples/sample.png'))),mask:manifest.screenshotMask});assert.deepEqual({width:result.width,height:result.height},{width:640,height:280});assert.equal(result.opaqueBlack,true);assert.equal(result.unmaskedUnchanged,true);assert.equal(result.unmaskedPixels,640*280-manifest.screenshotMask.width*manifest.screenshotMask.height);await writeFile(path.join(artifact,'clean-mask.png'),png);await page.screenshot({path:path.join(artifact,'review.png'),fullPage:true});});
 await step('JPEG becomes a fresh PNG without source EXIF',async()=>{await page.reload();await choose.setInputFiles(path.join(fixtureRoot,'examples/sample.jpg'));await ready(1);await fillReport();const zip=await download('jpeg-bundle.zip');const png=zip['evidence-001.png'];assert.ok(png);assert.ok(!Buffer.from(png).includes(Buffer.from('IMAGE_META_SEED_0123456789')));const image=await page.evaluate(async bytes=>{const b=await createImageBitmap(new Blob([new Uint8Array(bytes)],{type:'image/png'}));const r={width:b.width,height:b.height};b.close();return r;},Array.from(png));assert.deepEqual(image,{width:640,height:280});});
 await step('malformed evidence blocks export until removed',async()=>{await choose.setInputFiles({name:'bad.har',mimeType:'application/json',buffer:Buffer.from('{"log":{"version":"9.9","entries":[]}}')});await page.waitForFunction(()=>document.querySelectorAll('.status-failed').length===1);assert.equal(await exportButton.isEnabled(),false);await page.getByRole('button',{name:'Remove bad.har',exact:true}).click();assert.equal(await ack.isChecked(),false);await ack.check();assert.equal(await exportButton.isEnabled(),true);});
 await step('invalid UTF-8 and over-limit input fail explicitly',async()=>{await page.reload();await choose.setInputFiles({name:'invalid.log',mimeType:'text/plain',buffer:Buffer.from([0xc3,0x28])});await page.waitForFunction(()=>document.querySelectorAll('.status-failed').length===1);await page.getByRole('button',{name:'Remove invalid.log',exact:true}).click();await choose.setInputFiles({name:'too-large.log',mimeType:'text/plain',buffer:Buffer.alloc(16*1024*1024+1,65)});await page.waitForFunction(()=>document.querySelectorAll('.status-failed').length===1);assert.equal(await exportButton.isEnabled(),false);});
 await step('cancelling a paused actual worker cannot publish a stale result',async()=>{await page.reload();const cdp=await context.newCDPSession(page);let attachment;const attached=new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Actual comparison worker did not attach in debugger-paused state.')),5000);cdp.on('Target.attachedToTarget',event=>{if(event.targetInfo.type==='worker'){clearTimeout(timer);attachment=event;resolve(event);}});});await cdp.send('Target.setAutoAttach',{autoAttach:true,waitForDebuggerOnStart:true,flatten:true});try{await choose.setInputFiles([{name:'cancelled.log',mimeType:'text/plain',buffer:Buffer.from('token=CANCELLATION_SYNTHETIC_SECRET')},{name:'queued.log',mimeType:'text/plain',buffer:Buffer.from('normal later input')}]);const target=await attached;assert.equal(target.waitingForDebugger,true);assert.match(target.targetInfo.url,/processing\.worker-/);await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.status-failed').length===2&&document.querySelectorAll('.status-ready').length===0,null,{timeout:10000});const deadline=Date.now()+5000;let alive=true;while(alive&&Date.now()<deadline){alive=(await cdp.send('Target.getTargets')).targetInfos.some(x=>x.targetId===target.targetInfo.targetId);if(alive)await new Promise(r=>setTimeout(r,25));}assert.equal(alive,false,'The actual cancelled worker must disappear.');assert.equal(await exportButton.isEnabled(),false);await page.getByRole('button',{name:'Remove cancelled.log',exact:true}).click();await page.getByRole('button',{name:'Remove queued.log',exact:true}).click();assert.equal(await page.locator('.file-row').count(),0);}finally{await cdp.send('Target.setAutoAttach',{autoAttach:false,waitForDebuggerOnStart:false,flatten:true}).catch(()=>{});await cdp.detach();}});
 await step('source inputs and application assets remain byte-identical',async()=>{assert.deepEqual(await identities(),initial);if(packaged)assert.deepEqual(await inspectStaticPackage(packageArchive,appRoot),packageInspection,'The entire extracted package must remain byte-identical to its archive.');assert.deepEqual(pageErrors,[]);assert.deepEqual(external,[]);assert.equal(canaryHits,0);});
 clearInterval(sampler);
 const evidence={schemaVersion:1,suite:'actual-browser-mvp',status:'passed',version:pkg.version,packaged,platform:process.platform+'/'+process.arch,host:{osRelease:os.release(),architecture:os.arch(),node:process.version,chromium:browser.version()},sourceCommit,sourceState,startedAt,finishedAt:new Date().toISOString(),steps,identities:initial,...(packaged?{packageInspection}:{}),security:{loopbackOnly:true,chromiumSandboxRequested:true,connectSrcNone:true,canaryHits,unexpectedRequests:external},observations:{pageErrors,parentNodePeakRssBytes:peakRss,parentNodeRssSamplingMs:200,parentNodeRssScope:'Acceptance Node process only; does not measure total browser or worker memory.'}};
 await writeFile(path.join(artifact,'acceptance.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({status:'passed',artifact,steps:steps.length,packaged}));
} catch(error) {let visibleState; if(page){visibleState=await page.locator('body').innerText().catch(()=>null);await page.screenshot({path:path.join(artifact,'failure.png'),fullPage:true}).catch(()=>{});} await writeFile(path.join(artifact,'failure.json'),JSON.stringify({visibleState,status:'failed',packaged,sourceCommit,sourceState,startedAt,finishedAt:new Date().toISOString(),steps,error:String(error.stack??error),pageErrors,external},null,2)+'\n');throw error;}
finally {await browser?.close();if(server){server.kill();await new Promise(resolve=>{if(server.exitCode!==null)resolve();else server.once('exit',resolve);});}await new Promise(resolve=>canary.close(resolve));}
